# Generated by Django 5.2.3 on 2025-07-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alumno_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
